Repository emieldesmidt/trustchain-superapp, pull requests merged in 2020-04, with the labels that each got.

#2 WIP: Updated api
  .github/workflows/build.yml
  .gitignore
  FOC/.gitignore
  FOC/build.gradle
  FOC/consumer-rules.pro
  FOC/libs/jlibtorrent-1.2.5.0.jar
  FOC/libs/jlibtorrent-android-arm-1.2.5.0.jar
  FOC/libs/jlibtorrent-android-arm64-1.2.5.0.jar
  FOC/libs/jlibtorrent-android-x86-1.2.5.0.jar
  FOC/libs/jlibtorrent-android-x86_64-1.2.5.0.jar
  FOC/proguard-rules.pro
  FOC/src/androidTest/java/nl/tudelft/trustchain/FOC/ExampleInstrumentedTest.kt
  FOC/src/main/AndroidManifest.xml
  FOC/src/main/java/nl/tudelft/trustchain/FOC/BlankFragment.kt
  FOC/src/main/java/nl/tudelft/trustchain/FOC/MainActivityFOC.kt
  FOC/src/main/res/layout/activity_main_foc.xml
  FOC/src/main/res/layout/blank_fragment.xml
  FOC/src/main/res/layout/content_main_activity_foc.xml
  FOC/src/main/res/navigation/nav_graph_foc.xml
  FOC/src/main/res/values/dimens.xml
  FOC/src/main/res/values/strings.xml
  FOC/src/main/res/values/styles.xml
  FOC/src/test/java/nl/tudelft/trustchain/FOC/ExampleUnitTest.kt
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/nl/tudelft/trustchain/app/AppDefinition.kt
  common/build.gradle
  common/src/main/java/nl/tudelft/trustchain/common/DemoCommunity.kt
  common/src/main/java/nl/tudelft/trustchain/common/util/VotingHelper.kt
  common/src/main/res/drawable/ic_naruto.xml
  common/src/test/java/nl/tudelft/trustchain/common/util/VotingHelperTest.kt
  doc/AppTutorial.md
  settings.gradle
Labels: documentation, enhancement

#17 Voting mode toggle
  voting/src/main/java/nl/tudelft/trustchain/voting/VotingActivity.kt
  voting/src/main/java/nl/tudelft/trustchain/voting/VotingMode.kt
  voting/src/main/res/layout/initiate_dialog.xml
  voting/src/main/res/values/strings.xml
Labels: enhancement

#18 Add initial doc to dao branch
  common/README.md
  doc/voting/all-proposals.png
  doc/voting/cast-vote.png
  doc/voting/create-threshold-proposal.png
  doc/voting/create-yes-no-proposal.png
  doc/voting/new-proposals.png
  doc/voting/vote-has-been-cast.png
  voting/README.md
Labels: documentation

#39 limit input to 50 chars
  voting/src/main/res/layout/initiate_dialog.xml
Labels: enhancement, ui

#40 No key fix
  common/src/main/java/nl/tudelft/trustchain/common/util/VotingHelper.kt
  voting/src/main/java/nl/tudelft/trustchain/voting/BlockListAdapter.kt
  voting/src/main/java/nl/tudelft/trustchain/voting/VotingActivity.kt
Labels: api, bug, voting-module

#38 New indicator
  common/src/main/java/nl/tudelft/trustchain/common/util/VotingHelper.kt
  voting/src/main/java/nl/tudelft/trustchain/voting/BlockListAdapter.kt
  voting/src/main/java/nl/tudelft/trustchain/voting/VotingActivity.kt
  voting/src/main/res/layout/proposal_block.xml
  voting/src/main/res/layout/vote_block.xml
Labels: api, enhancement, ui, voting-module

#46 Renaming
  app/build.gradle
  app/src/main/java/nl/tudelft/trustchain/app/AppDefinition.kt
  common/README.md
  common/src/main/java/nl/tudelft/trustchain/common/util/VotingHelper.kt
  common/src/test/java/nl/tudelft/trustchain/common/util/VotingHelperTest.kt
  settings.gradle
  trustchain-voter/.gitignore
  trustchain-voter/README.md
  trustchain-voter/build.gradle
  trustchain-voter/consumer-rules.pro
  trustchain-voter/proguard-rules.pro
  trustchain-voter/src/androidTest/java/nl/tudelft/trustchain/voting/ExampleInstrumentedTest.kt
  trustchain-voter/src/main/AndroidManifest.xml
  trustchain-voter/src/main/java/nl/tudelft/trustchain/voting/BlockListAdapter.kt
  trustchain-voter/src/main/java/nl/tudelft/trustchain/voting/VotingActivity.kt
  trustchain-voter/src/main/java/nl/tudelft/trustchain/voting/VotingCommunity.kt
  trustchain-voter/src/main/java/nl/tudelft/trustchain/voting/VotingFragment.kt
  trustchain-voter/src/main/res/layout/activity_main_voting.xml
  trustchain-voter/src/main/res/layout/blank_fragment.xml
  trustchain-voter/src/main/res/layout/initiate_dialog.xml
  trustchain-voter/src/main/res/layout/proposal_block.xml
  trustchain-voter/src/main/res/navigation/nav_graph_voting.xml
  trustchain-voter/src/main/res/values/strings.xml
  trustchain-voter/src/main/res/values/styles.xml
  trustchain-voter/src/test/java/nl/tudelft/trustchain/voting/ExampleUnitTest.kt
Labels: api, enhancement, ui, voting-module

#44 Updated the imagery and text in the README.md
  README.md
  common/README.md
  trustchain-voter/README.md
Labels: documentation

#47 Move images to repo
  README.md
  doc/trustchain-voter/cast-vote-process.gif
  doc/trustchain-voter/cast-vote-threshold.png
  doc/trustchain-voter/cast-vote-yes-no.png
  doc/trustchain-voter/create-proposal.gif
  doc/trustchain-voter/foc-demo.gif
  doc/trustchain-voter/user-toggle.gif
  doc/voting/all-proposals.png
  doc/voting/cast-vote.png
  doc/voting/create-threshold-proposal.png
  doc/voting/create-yes-no-proposal.png
  doc/voting/new-proposals.png
  doc/voting/vote-has-been-cast.png
  trustchain-voter/README.md
Labels: documentation

#48 Half block fix
  common/src/main/java/nl/tudelft/trustchain/common/util/VotingHelper.kt
  trustchain-voter/src/main/java/nl/tudelft/trustchain/voting/VotingActivity.kt
Labels: bug, enhancement, prio::high
